export const FETCH_MOVIES='FETCH_MOVIES';
export const SELECT_DISPLAY='SELECT_DISPLAY';
export const ADD_MOVIE_BUTTON='ADD_MOVIE_BUTTON';
export const TYPE_NEW_MOVIE='TYPE_NEW_MOVIE';
export const SELECT_MOVIE='SELECT_MOVIE';
export const CLOSE_ADD_INPUT="CLOSE_ADD_INPUT";
export const ADD_MOVIE='ADD_MOVIE';
export const REMOVE_MOVIE='REMOVE_MOVIE';